// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace StudentAtendances.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250303182100_UpdateAttendanceWithDate")]
    partial class UpdateAttendanceWithDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentAtendances.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolYears")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupName = "CNTT",
                            LecturerId = 1,
                            Major = "IT",
                            SchoolYears = "2023-2024"
                        },
                        new
                        {
                            Id = 2,
                            GroupName = "QTKD",
                            LecturerId = 2,
                            Major = "Business",
                            SchoolYears = "2023-2024"
                        });
                });

            modelBuilder.Entity("StudentAtendances.Models.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Lecturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "a@example.com",
                            Name = "Nguyen Van A",
                            Password = "hashedpassword1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "b@example.com",
                            Name = "Tran Thi B",
                            Password = "hashedpassword2"
                        });
                });

            modelBuilder.Entity("StudentAtendances.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupId = 1,
                            Name = "Student 1",
                            StudentCode = "SV001",
                            StudyCode = "SC001"
                        },
                        new
                        {
                            Id = 2,
                            GroupId = 1,
                            Name = "Student 2",
                            StudentCode = "SV002",
                            StudyCode = "SC002"
                        },
                        new
                        {
                            Id = 3,
                            GroupId = 1,
                            Name = "Student 3",
                            StudentCode = "SV003",
                            StudyCode = "SC003"
                        },
                        new
                        {
                            Id = 4,
                            GroupId = 1,
                            Name = "Student 4",
                            StudentCode = "SV004",
                            StudyCode = "SC004"
                        },
                        new
                        {
                            Id = 5,
                            GroupId = 1,
                            Name = "Student 5",
                            StudentCode = "SV005",
                            StudyCode = "SC005"
                        },
                        new
                        {
                            Id = 6,
                            GroupId = 2,
                            Name = "Student 6",
                            StudentCode = "SV006",
                            StudyCode = "SC006"
                        },
                        new
                        {
                            Id = 7,
                            GroupId = 2,
                            Name = "Student 7",
                            StudentCode = "SV007",
                            StudyCode = "SC007"
                        },
                        new
                        {
                            Id = 8,
                            GroupId = 2,
                            Name = "Student 8",
                            StudentCode = "SV008",
                            StudyCode = "SC008"
                        },
                        new
                        {
                            Id = 9,
                            GroupId = 2,
                            Name = "Student 9",
                            StudentCode = "SV009",
                            StudyCode = "SC009"
                        },
                        new
                        {
                            Id = 10,
                            GroupId = 2,
                            Name = "Student 10",
                            StudentCode = "SV010",
                            StudyCode = "SC010"
                        });
                });

            modelBuilder.Entity("StudentAtendances.Models.StudentSubjectAttendance", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.HasKey("StudentId", "SubjectId", "Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubjectAttendances");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            SubjectId = 1,
                            Id = 1,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 1,
                            Id = 2,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 1,
                            Id = 3,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 1,
                            Id = 4,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 1,
                            Id = 5,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 1,
                            Id = 6,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 1,
                            Id = 7,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 1,
                            Id = 8,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 1,
                            Id = 9,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 1,
                            Id = 10,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 1,
                            Id = 11,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 1,
                            Id = 12,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 1,
                            Id = 13,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 1,
                            Id = 14,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 1,
                            Id = 15,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 1,
                            Id = 16,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 1,
                            Id = 17,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 1,
                            Id = 18,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 2,
                            Id = 19,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 2,
                            Id = 20,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 2,
                            Id = 21,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 2,
                            Id = 22,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 2,
                            Id = 23,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 2,
                            Id = 24,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 2,
                            Id = 25,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 2,
                            Id = 26,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 2,
                            Id = 27,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 2,
                            Id = 28,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 2,
                            Id = 29,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 2,
                            Id = 30,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 2,
                            Id = 31,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 2,
                            Id = 32,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 2,
                            Id = 33,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 2,
                            Id = 34,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 2,
                            Id = 35,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 2,
                            Id = 36,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 3,
                            Id = 37,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 3,
                            Id = 38,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 3,
                            Id = 39,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 3,
                            Id = 40,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 3,
                            Id = 41,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 3,
                            Id = 42,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 3,
                            Id = 43,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 3,
                            Id = 44,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 3,
                            Id = 45,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 3,
                            Id = 46,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 3,
                            Id = 47,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 3,
                            Id = 48,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 3,
                            Id = 49,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 3,
                            Id = 50,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 3,
                            Id = 51,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 3,
                            Id = 52,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 3,
                            Id = 53,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 3,
                            Id = 54,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 4,
                            Id = 55,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 4,
                            Id = 56,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 4,
                            Id = 57,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 4,
                            Id = 58,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 4,
                            Id = 59,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 4,
                            Id = 60,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 4,
                            Id = 61,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 4,
                            Id = 62,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 4,
                            Id = 63,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 4,
                            Id = 64,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 4,
                            Id = 65,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 4,
                            Id = 66,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 4,
                            Id = 67,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 4,
                            Id = 68,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 4,
                            Id = 69,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 4,
                            Id = 70,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 4,
                            Id = 71,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 4,
                            Id = 72,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 5,
                            Id = 73,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 5,
                            Id = 74,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 5,
                            Id = 75,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 5,
                            Id = 76,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 5,
                            Id = 77,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 5,
                            Id = 78,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 5,
                            Id = 79,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 5,
                            Id = 80,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 5,
                            Id = 81,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 5,
                            Id = 82,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 5,
                            Id = 83,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 5,
                            Id = 84,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 5,
                            Id = 85,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 5,
                            Id = 86,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 5,
                            Id = 87,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 5,
                            Id = 88,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 5,
                            Id = 89,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 5,
                            Id = 90,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 6,
                            Id = 91,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 6,
                            Id = 92,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 6,
                            Id = 93,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 6,
                            Id = 94,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 6,
                            Id = 95,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 6,
                            Id = 96,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 6,
                            Id = 97,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 6,
                            Id = 98,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 6,
                            Id = 99,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 6,
                            Id = 100,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 6,
                            Id = 101,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 6,
                            Id = 102,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 6,
                            Id = 103,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 6,
                            Id = 104,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 6,
                            Id = 105,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 6,
                            Id = 106,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 6,
                            Id = 107,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 6,
                            Id = 108,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true
                        });
                });

            modelBuilder.Entity("StudentAtendances.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LecturerId = 1,
                            SubjectCode = "IT101",
                            SubjectName = "Lập trình C#"
                        },
                        new
                        {
                            Id = 2,
                            LecturerId = 1,
                            SubjectCode = "IT102",
                            SubjectName = "Cấu trúc dữ liệu"
                        },
                        new
                        {
                            Id = 3,
                            LecturerId = 1,
                            SubjectCode = "IT103",
                            SubjectName = "SQL Server"
                        },
                        new
                        {
                            Id = 4,
                            LecturerId = 2,
                            SubjectCode = "BUS201",
                            SubjectName = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            LecturerId = 2,
                            SubjectCode = "BUS202",
                            SubjectName = "Quản lý tài chính"
                        },
                        new
                        {
                            Id = 6,
                            LecturerId = 2,
                            SubjectCode = "BUS203",
                            SubjectName = "Kinh tế vi mô"
                        });
                });

            modelBuilder.Entity("StudentAtendances.Models.Group", b =>
                {
                    b.HasOne("StudentAtendances.Models.Lecturer", "Lecturer")
                        .WithMany("Groups")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("StudentAtendances.Models.Student", b =>
                {
                    b.HasOne("StudentAtendances.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("StudentAtendances.Models.StudentSubjectAttendance", b =>
                {
                    b.HasOne("StudentAtendances.Models.Student", "Student")
                        .WithMany("StudentSubjectAttendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentAtendances.Models.Subject", "Subject")
                        .WithMany("StudentSubjectAttendances")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentAtendances.Models.Subject", b =>
                {
                    b.HasOne("StudentAtendances.Models.Lecturer", "Lecturer")
                        .WithMany("Subjects")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("StudentAtendances.Models.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentAtendances.Models.Lecturer", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("StudentAtendances.Models.Student", b =>
                {
                    b.Navigation("StudentSubjectAttendances");
                });

            modelBuilder.Entity("StudentAtendances.Models.Subject", b =>
                {
                    b.Navigation("StudentSubjectAttendances");
                });
#pragma warning restore 612, 618
        }
    }
}
